# Generated by Django 3.1.6 on 2023-10-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followers',
            new_name='Follower',
        ),
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
        migrations.AddField(
            model_name='author',
            name='streamPosts',
            field=models.ManyToManyField(blank=True, related_name='inboxes', to='project.Post'),
        ),
    ]
