# Generated by Django 3.1.6 on 2023-10-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20231017_2245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inbox',
        ),
    ]
