# Generated by Django 3.1.6 on 2023-10-23 04:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20231023_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.URLField(default='https://i.imgur.com/k7XVwpB.jpeg'),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
