# Generated by Django 3.1.6 on 2023-11-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20231027_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
    ]
