# Generated by Django 4.2.7 on 2023-11-30 22:18

from django.db import migrations
from django.db.models import Q, F


def populate_display_name(apps, schema_editor):
    Author = apps.get_model("project", "Author")
    authors = list(Author.objects.filter(Q(displayName__isnull=True) | Q(displayName="")).select_related("user"))
    for author in authors:
        author.displayName = author.user.username
    Author.objects.bulk_update(authors, ["displayName"])


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0011_alter_comment_published_alter_post_published"),
    ]

    operations = [
        migrations.RunPython(populate_display_name, migrations.RunPython.noop)
    ]
