# Generated by Django 4.2.7 on 2023-11-26 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0011_alter_comment_published_alter_post_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='nodeCred',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='node',
            name='user',
            field=models.OneToOneField(default=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='node',
            name='apiURL',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='nodeName',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
