# Generated by Django 4.2.7 on 2023-11-26 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0012_node_nodecred_node_user_alter_node_apiurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
