# Generated by Django 4.2.7 on 2023-12-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0012_populate_author_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(default=""),
        ),
    ]
