# Generated by Django 4.2.6 on 2023-12-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_alter_author_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/plain', 'Text'), ('text/markdown', 'CommonMark'), ('image/png;base64', 'PNG'), ('image/jpeg;base64', 'JPEG')], max_length=200),
        ),
    ]
