# Generated by Django 4.2.6 on 2023-12-03 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_alter_post_content'),
        ('project', '0015_alter_post_content_alter_post_contenttype'),
    ]

    operations = [
    ]
