# Generated by Django 4.2.6 on 2023-12-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_merge_20231203_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
