# Generated by Django 4.2.7 on 2023-12-04 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_post_private_reciever'),
        ('project', '0017_alter_post_content'),
    ]

    operations = [
    ]
