# Generated by Django 4.2.7 on 2023-12-04 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_merge_20231203_1954'),
        ('project', '0018_notification'),
    ]

    operations = [
    ]
