# Generated by Django 4.2.7 on 2023-12-08 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_merge_20231203_2122'),
        ('project', '0019_merge_0016_merge_20231203_1954_0018_notification'),
    ]

    operations = [
    ]
